apiVersion: apps/v1
kind: Deployment
metadata:
  name: prog-acad-api
spec:
  selector:
    matchLabels:
      app: prog-acad-api
  replicas: 1
  template:
    metadata:
      labels:
        app: prog-acad-api
    spec:
      containers:
      - name: prog-acad-api
        image: okteto.dev/prog-acad-api:latest
        ports:
        - containerPort: 8080
